/* Projeto MPS - Cadastro de pilotos de aeronave
 * 
 * Professora: Raoni Kulesza
 * 
 * Grupo: Angelina Sales
          Jorismar Barbosa
          Nycholas de Sousa
 * 
 * Descrição da Classe: Classe responsável por procurar e alterar o cadastro caso sejá necessário.
 */
package cadastroPilotos;

import piloto.ExpProfissional;
import piloto.Piloto;
import piloto.TipoAeronave;
import piloto.CHT;
import java.util.LinkedList;
import javax.swing.JOptionPane;

/**
 *
 * @author caiomcg
 */
public class Alterar extends javax.swing.JInternalFrame {

    /**
     * Creates new form Alterar
     */
    private int indice = -1; //apenas para saber se nao achou nenhum registro
    private Piloto p;
    private CHT t;
    private ExpProfissional exp;
    private TipoAeronave aeronave;
    private int indiceTitulacao = 0;
    private int indiceExpProfissional = 0;
    private int indiceTipoAeronave = 0;
    private LinkedList<Piloto> listaPilotos;

    public Alterar() {
        initComponents(); //Default NetBeans
        setSize(1024, 904); //Tamanho da tela
        listaPilotos = Persistencia.getListaPiloto();
        pesquisar.setToolTipText("Pesquisar brevê."); //Mostra informações sobre o botão para o usuário
        alterarDadosPessoais.setToolTipText("Confirmar alteração."); //Mostra informações sobre o botão para o usuário
        alterarExperienciaProfissional.setToolTipText("Confirmar alteração."); //Mostra informações sobre o botão para o usuário
        alterarTipoDeAeronave.setToolTipText("Confirmar alteração."); //Mostra informações sobre o botão para o usuário
        alterarTitulacao.setToolTipText("Confirmar alteração."); //Mostra informações sobre o botão para o usuário
        jButton1.setToolTipText("Clique no botão para exibir mais informações."); //Mostra informações sobre o botão para o usuário
        jButton2.setToolTipText("Clique no botão para exibir mais informações."); //Mostra informações sobre o botão para o usuário
        jButton3.setToolTipText("Clique no botão para exibir mais informações."); //Mostra informações sobre o botão para o usuário
        jButton1.setEnabled(false); //Desabilita o botão
        jButton2.setEnabled(false); //Desabilita o botão
        jButton3.setEnabled(false); //Desabilita o botão
        nome.setEditable(false);
        endereco.setEditable(false);
        fone.setEditable(false);
        email.setEditable(false);
        nBreve.setEditable(false);
        registroProf.setEditable(false);
        anoConc.setEditable(false);
        nomeInt.setEditable(false);
        cidade.setEditable(false);
        uf.setEditable(false);
        dInicio.setEditable(false);
        dTermino.setEditable(false);
        empresa.setEditable(false);
        nCidade.setEditable(false);
        estado.setEditable(false);
        descricao.setEditable(false);
        modelo.setEditable(false);
        cPassageiros.setEditable(false);
        hVoo.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        pesquisar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Nome = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        Endereco = new javax.swing.JLabel();
        endereco = new javax.swing.JTextField();
        Registro = new javax.swing.JLabel();
        fone = new javax.swing.JFormattedTextField();
        Email = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        Breve = new javax.swing.JLabel();
        nBreve = new javax.swing.JTextField();
        Fone = new javax.swing.JLabel();
        registroProf = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        Breve1 = new javax.swing.JLabel();
        anoConc = new javax.swing.JFormattedTextField();
        nomeInt = new javax.swing.JTextField();
        Breve2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Breve3 = new javax.swing.JLabel();
        Breve4 = new javax.swing.JLabel();
        cidade = new javax.swing.JTextField();
        uf = new javax.swing.JFormattedTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        descricao = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        dInicio = new javax.swing.JFormattedTextField();
        dTermino = new javax.swing.JFormattedTextField();
        empresa = new javax.swing.JTextField();
        nCidade = new javax.swing.JTextField();
        estado = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        modelo = new javax.swing.JTextField();
        cPassageiros = new javax.swing.JTextField();
        hVoo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        alterarTitulacao = new javax.swing.JButton();
        alterarExperienciaProfissional = new javax.swing.JButton();
        alterarTipoDeAeronave = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        alterarDadosPessoais = new javax.swing.JButton();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Alterar");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/cadastroPilotos/imagens/aviao.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Digite o número do brevê para procurar um piloto:");

        pesquisar.setText("Pesquisar");
        pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Dados Pessoais:");

        Nome.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Nome.setText("Nome: ");

        nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeActionPerformed(evt);
            }
        });

        Endereco.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Endereco.setText("Endereço:");

        Registro.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Registro.setText("Fone:");

        try {
            fone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        Email.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Email.setText("E-mail:");

        Breve.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Breve.setText("Número do Brevê:");

        nBreve.setName(""); // NOI18N
        nBreve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nBreveActionPerformed(evt);
            }
        });

        Fone.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Fone.setText("Registro Profissional:");

        Breve1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Breve1.setText("Ano de Conclusão:");

        try {
            anoConc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        Breve2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Breve2.setText("Nome da Instituição:");

        jButton1.setText(">>>");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Breve3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Breve3.setText("Cidade:");

        Breve4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Breve4.setText("UF:");

        try {
            uf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("UU")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        descricao.setColumns(20);
        descricao.setRows(5);
        jScrollPane1.setViewportView(descricao);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel10.setText("Descrição da Atividade:");

        try {
            dInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            dTermino.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Experiência Profissional:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("Data de Início:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setText("Data de Término:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setText("Empresa:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel8.setText("Cidade:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel9.setText("Estado:");

        jButton2.setText(">>>");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Tipo de Aeronave:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel12.setText("Modelo:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel13.setText("Capacidade de Passageiros:");

        hVoo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hVooActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel14.setText("Horas de Vôo:");

        jButton3.setText(">>>");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        alterarTitulacao.setText("Alterar");
        alterarTitulacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarTitulacaoActionPerformed(evt);
            }
        });

        alterarExperienciaProfissional.setText("Alterar");
        alterarExperienciaProfissional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarExperienciaProfissionalActionPerformed(evt);
            }
        });

        alterarTipoDeAeronave.setText("Alterar");
        alterarTipoDeAeronave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarTipoDeAeronaveActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Titulação:");

        alterarDadosPessoais.setText("Alterar");
        alterarDadosPessoais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarDadosPessoaisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Breve)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nBreve, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Fone)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(registroProf))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Endereco)
                                    .addComponent(Nome))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nome)
                                    .addComponent(endereco)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Email)
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fone)
                                    .addComponent(email))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pesquisar)
                        .addGap(74, 74, 74))
                    .addComponent(jSeparator3)
                    .addComponent(jSeparator4)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(Registro)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Breve1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(anoConc))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Breve2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(nomeInt, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Breve3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Breve4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(uf, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel11)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(hVoo))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cPassageiros, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(dInicio))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(dTermino, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel9))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(estado)
                                            .addComponent(nCidade)
                                            .addComponent(empresa, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(12, 12, 12)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3)
                            .addComponent(alterarDadosPessoais)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(alterarTitulacao))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(alterarExperienciaProfissional))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(alterarTipoDeAeronave)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Endereco))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Registro)
                    .addComponent(fone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Email))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Fone)
                    .addComponent(nBreve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Breve)
                    .addComponent(registroProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alterarDadosPessoais)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Breve1)
                    .addComponent(Breve3)
                    .addComponent(anoConc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Breve2)
                    .addComponent(Breve4)
                    .addComponent(nomeInt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(alterarTitulacao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(dInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addComponent(dTermino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(empresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(nCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(alterarExperienciaProfissional))
                .addGap(19, 19, 19)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(cPassageiros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(hVoo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(alterarTipoDeAeronave))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeActionPerformed

    private void nBreveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nBreveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nBreveActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        indiceTitulacao++;
        if (Persistencia.getListaPiloto().get(indice).getTitulacao().size() == indiceTitulacao) {
            indiceTitulacao = 0;
        }
        t = Persistencia.getListaPiloto().get(indice).getTitulacao().get(indiceTitulacao);
        anoConc.setText(String.valueOf(p.getTitulacao().get(indiceTitulacao).getAnoConclusao())); //Retira a função de edição do campo de texto
        nomeInt.setText(p.getTitulacao().get(indiceTitulacao).getNomeInstituicao()); //Retira a função de edição do campo de texto
        cidade.setText(p.getTitulacao().get(indiceTitulacao).getCidade()); //Retira a função de edição do campo de texto
        uf.setText(p.getTitulacao().get(indiceTitulacao).getuF()); //Retira a função de edição do campo de texto
    }//GEN-LAST:event_jButton1ActionPerformed

    private void pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarActionPerformed
        // TODO add your handling code here:
        indice = -1;

        for (int i = 0; i < Persistencia.getListaPiloto().size(); i++) {
            if (Persistencia.getListaPiloto().get(i).getBreve().equalsIgnoreCase(jTextField1.getText())) {
                jButton1.setEnabled(true); //Reabilita o botão
                jButton2.setEnabled(true); //Reabilita o botão
                jButton3.setEnabled(true); //Reabilita o botão
                nome.setEditable(true);
                endereco.setEditable(true);
                fone.setEditable(true);
                email.setEditable(true);
                anoConc.setEditable(true);
                nomeInt.setEditable(true);
                cidade.setEditable(true);
                uf.setEditable(true);
                dInicio.setEditable(true);
                dTermino.setEditable(true);
                empresa.setEditable(true);
                nCidade.setEditable(true);
                estado.setEditable(true);
                descricao.setEditable(true);
                modelo.setEditable(true);
                cPassageiros.setEditable(true);
                hVoo.setEditable(true);

                indice = i;

                p = Persistencia.getListaPiloto().get(indice);
                t = Persistencia.getListaPiloto().get(indice).getTitulacao().get(indiceTitulacao);
                exp = Persistencia.getListaPiloto().get(indice).getExpProfissional().get(indiceExpProfissional);
                aeronave = Persistencia.getListaPiloto().get(indice).getTipoAeronave().get(indiceTipoAeronave);

                //dados pessoais
                nome.setText(p.getNome());
                endereco.setText(p.getEndereco());
                fone.setText(p.getFone());
                fone.setValue(p.getFone());
                email.setText(p.getMail());
                nBreve.setText(p.getBreve());
                registroProf.setText(p.getRegistroP());
                //titulacao
                anoConc.setText(String.valueOf(t.getAnoConclusao()));
                nomeInt.setText(t.getNomeInstituicao());
                cidade.setText(t.getCidade());
                uf.setText(t.getuF());

                //exp
                dInicio.setText(exp.getDataI());
                dTermino.setText(exp.getDataT());
                empresa.setText(exp.getEmpresa());
                nCidade.setText(exp.getNCidade());
                estado.setText(exp.getEstado());
                descricao.setText(exp.getDescricaoA());

                //aeronave
                modelo.setText(aeronave.getModelo());
                cPassageiros.setText(String.valueOf(aeronave.getCapacidadePassageiros()));
                hVoo.setText(String.valueOf(aeronave.getHorasDeVoo()));

                break;
            }
        }

        if (indice == -1) {
            JOptionPane.showMessageDialog(null, "nada foi encontrado");
        }
    }//GEN-LAST:event_pesquisarActionPerformed

    private void alterarDadosPessoaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarDadosPessoaisActionPerformed
        // TODO add your handling code here:
        if (((nome.getText().length() <= 0)) || ((endereco.getText().length() <= 0)) || ((fone.getText().length() <= 0))
                || ((email.getText().length() <= 0)) || ((nBreve.getText().length() <= 0)) || ((registroProf.getText().length() <= 0))) {
            JOptionPane.showMessageDialog(null, "Todos os campos devem ser preenchidos para alterar o cadastro", "Erro", JOptionPane.ERROR_MESSAGE);
        } else {
            p.setBreve(nBreve.getText());
            p.setNome(nome.getText());
            p.setEndereco(endereco.getText());
            p.setFone(fone.getText());
            p.setMail(email.getText());
            p.setRegistroP(registroProf.getText());

            Persistencia.getListaPiloto().set(indice, p);
        }

    }//GEN-LAST:event_alterarDadosPessoaisActionPerformed

    private void alterarTitulacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarTitulacaoActionPerformed
        if (Persistencia.checkDataTit(anoConc.getText())) {
            JOptionPane.showMessageDialog(null, "O ano usado não é possível", "Erro", JOptionPane.ERROR_MESSAGE);
        } else {
            if (((anoConc.getText().length() <= 0)) || ((nomeInt.getText().length() <= 0))
                    || ((cidade.getText().length() <= 0)) || ((uf.getText().length() <= 0))) { //Verifica se existem campos vazios. Se existirem mostra a mensagem abaixo ao usuário.
                JOptionPane.showMessageDialog(null, "Todos os campos devem ser preenchidos para alterar o cadastro", "Erro", JOptionPane.ERROR_MESSAGE);
            } else {

                t.setAnoConclusao(Integer.parseInt(anoConc.getText()));
                t.setCidade(cidade.getText());
                t.setNomeInstituicao(nomeInt.getText());
                t.setuF(uf.getText());

                Persistencia.getListaPiloto().get(indice).getTitulacao().set(indiceTitulacao, t);
            }
        }
    }//GEN-LAST:event_alterarTitulacaoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        indiceExpProfissional++;
        if (Persistencia.getListaPiloto().get(indice).getExpProfissional().size() == indiceExpProfissional) {
            indiceExpProfissional = 0;
        }
        exp = Persistencia.getListaPiloto().get(indice).getExpProfissional().get(indiceExpProfissional);
        dInicio.setText(exp.getDataI()); //Retira a função de edição do campo de texto
        dTermino.setText(exp.getDataT()); //falta adicionar na tela cadastro
        empresa.setText(exp.getEmpresa());
        nCidade.setText(exp.getNCidade());
        estado.setText(exp.getEstado());
        descricao.setText(exp.getDescricaoA());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void alterarExperienciaProfissionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarExperienciaProfissionalActionPerformed
        if (((dInicio.getText().length() <= 0))
                || ((descricao.getText().length() <= 0)) || ((empresa.getText().length() <= 0))
                || ((nCidade.getText().length() <= 0)) || ((estado.getText().length() <= 0))) { //Verifica se existem campos vazios. Se existirem mostra a mensagem abaixo ao usuário.
            JOptionPane.showMessageDialog(null, "Todos os campos devem ser preenchidos para continuar o cadastro", "Erro", JOptionPane.ERROR_MESSAGE);
        } else { //Se os campos estiverem preenchidos realiza o código abaixo
            if (dTermino.getText().equals("  /  /    ")) {
                dTermino.setValue("00/00/0000");
                dTermino.getText();
            }
            exp.setDataI(dInicio.getText());
            exp.setDataT(dTermino.getText());
            exp.setEmpresa(empresa.getText());
            exp.setnCidade(nCidade.getText());
            exp.setEstado(estado.getText());
            exp.setDescricaoA(descricao.getText());
            Persistencia.getListaPiloto().get(indice).getExpProfissional().set(indiceExpProfissional, exp);
        }
    }//GEN-LAST:event_alterarExperienciaProfissionalActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        indiceTipoAeronave++;
        if (Persistencia.getListaPiloto().get(indice).getTipoAeronave().size() == indiceTipoAeronave) {
            indiceTipoAeronave = 0;
        }
        aeronave = Persistencia.getListaPiloto().get(indice).getTipoAeronave().get(indiceTipoAeronave);
        modelo.setText(aeronave.getModelo());
        cPassageiros.setText(String.valueOf(aeronave.getCapacidadePassageiros()));
        hVoo.setText(String.valueOf(aeronave.getHorasDeVoo()));
    }//GEN-LAST:event_jButton3ActionPerformed

    private void alterarTipoDeAeronaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarTipoDeAeronaveActionPerformed
        if (((modelo.getText().length() <= 0)) || ((cPassageiros.getText().length() <= 0))
                || ((hVoo.getText().length() <= 0))) { //Verifica se existem campos vazios. Se existirem mostra a mensagem abaixo ao usuário.
            JOptionPane.showMessageDialog(null, "Todos os campos devem ser preenchidos para continuar o cadastro", "Erro", JOptionPane.ERROR_MESSAGE);
        } else {

        aeronave.setModelo(modelo.getText());
        aeronave.setCapacidadePassageiros(Integer.parseInt(cPassageiros.getText()));
        aeronave.setHorasDeVoo(Integer.parseInt(hVoo.getText()));

        Persistencia.getListaPiloto().get(indice).getTipoAeronave().set(indiceTipoAeronave, aeronave);
        }
    }//GEN-LAST:event_alterarTipoDeAeronaveActionPerformed

    private void hVooActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hVooActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hVooActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Breve;
    private javax.swing.JLabel Breve1;
    private javax.swing.JLabel Breve2;
    private javax.swing.JLabel Breve3;
    private javax.swing.JLabel Breve4;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel Endereco;
    private javax.swing.JLabel Fone;
    private javax.swing.JLabel Nome;
    private javax.swing.JLabel Registro;
    private javax.swing.JButton alterarDadosPessoais;
    private javax.swing.JButton alterarExperienciaProfissional;
    private javax.swing.JButton alterarTipoDeAeronave;
    private javax.swing.JButton alterarTitulacao;
    private javax.swing.JFormattedTextField anoConc;
    private javax.swing.JTextField cPassageiros;
    private javax.swing.JTextField cidade;
    private javax.swing.JFormattedTextField dInicio;
    private javax.swing.JFormattedTextField dTermino;
    private javax.swing.JTextArea descricao;
    private javax.swing.JTextField email;
    private javax.swing.JTextField empresa;
    private javax.swing.JTextField endereco;
    private javax.swing.JTextField estado;
    private javax.swing.JFormattedTextField fone;
    private javax.swing.JTextField hVoo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField modelo;
    private javax.swing.JTextField nBreve;
    private javax.swing.JTextField nCidade;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField nomeInt;
    private javax.swing.JButton pesquisar;
    private javax.swing.JTextField registroProf;
    private javax.swing.JFormattedTextField uf;
    // End of variables declaration//GEN-END:variables
}
