/* Projeto MPS - Cadastro de pilotos de aeronave
 * 
 * Professora: Raoni Kulesza
 * 
 * Grupo: Angelina Sales
          Jorismar Barbosa
          Nycholas de Sousa
 * 
 * Descrição da Classe: Classe responável pela consulta de dados
 */
package cadastroPilotos;

import piloto.ExpProfissional;
import piloto.Piloto;
import piloto.TipoAeronave;
import piloto.CHT;
import java.util.LinkedList;
import javax.swing.JOptionPane;

public class Consulta extends javax.swing.JInternalFrame {

    /**
     * Creates new form Consulta
     */
    private int indice;
    private int indiceTitulacao = 0;
    private int indiceExpProfissional = 0;
    private int indiceTipoAeronave = 0;
    private LinkedList<Piloto> listaPilotos;
    private boolean encontrou;
    private Piloto p;
    private CHT t;
    private ExpProfissional exp;
    private TipoAeronave aeronave;

    public Consulta() {
        if (Persistencia.getListaPiloto() != null) {
            listaPilotos = Persistencia.getListaPiloto();
        }
        Persistencia.setupLer();
        Persistencia.readRecords();

        initComponents(); //Default NetBeans
        setSize(1000, 880); //Tamanho da tela
        proxTitulacao.setToolTipText("Clique no botão para exibir mais informações."); //Mostra informações sobre o botão para o usuário
        proxExpProf.setToolTipText("Clique no botão para exibir mais informações."); //Mostra informações sobre o botão para o usuário
        proxTipoAeronave.setToolTipText("Clique no botão para exibir mais informações."); //Mostra informações sobre o botão para o usuário
        pesquisar.setToolTipText("Pesquisar brevê."); //Mostra informações sobre o botão para o usuário

        nome.setEditable(false); //Retira a função de edição do campo de texto
        endereco.setEditable(false); //Retira a função de edição do campo de texto
        fone.setEditable(false); //Retira a função de edição do campo de texto
        email.setEditable(false); //Retira a função de edição do campo de texto
        nBreve.setEditable(false); //Retira a função de edição do campo de texto
        registroProf.setEditable(false); //Retira a função de edição do campo de texto
        anoConc.setEditable(false); //Retira a função de edição do campo de texto
        nomeInt.setEditable(false); //Retira a função de edição do campo de texto
        cidade.setEditable(false); //Retira a função de edição do campo de texto
        uf.setEditable(false); //Retira a função de edição do campo de texto
        dInicio.setEditable(false); //Retira a função de edição do campo de texto
        dTermino.setEditable(false); //Retira a função de edição do campo de texto
        empresa.setEditable(false); //Retira a função de edição do campo de texto
        nCidade.setEditable(false); //Retira a função de edição do campo de texto
        estado.setEditable(false); //Retira a função de edição do campo de texto
        descricao.setEditable(false); //Retira a função de edição do campo de texto
        modelo.setEditable(false); //Retira a função de edição do campo de texto
        cPassageiros.setEditable(false); //Retira a função de edição do campo de texto
        hVoo.setEditable(false); //Retira a função de edição do campo de texto

        proxExpProf.setEnabled(false); //Desabilita o botão
        proxTipoAeronave.setEnabled(false); //Desabilita o botão
        proxTitulacao.setEnabled(false); //Desabilita o botão
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        Nome = new javax.swing.JLabel();
        endereco = new javax.swing.JTextField();
        Endereco = new javax.swing.JLabel();
        fone = new javax.swing.JFormattedTextField();
        Registro = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        Email = new javax.swing.JLabel();
        Breve = new javax.swing.JLabel();
        nBreve = new javax.swing.JTextField();
        Fone = new javax.swing.JLabel();
        registroProf = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        Breve1 = new javax.swing.JLabel();
        anoConc = new javax.swing.JFormattedTextField();
        Breve2 = new javax.swing.JLabel();
        cidade = new javax.swing.JTextField();
        Breve3 = new javax.swing.JLabel();
        uf = new javax.swing.JFormattedTextField();
        Breve4 = new javax.swing.JLabel();
        nomeInt = new javax.swing.JTextField();
        proxTitulacao = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dInicio = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        dTermino = new javax.swing.JFormattedTextField();
        empresa = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        nCidade = new javax.swing.JTextField();
        estado = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descricao = new javax.swing.JTextArea();
        proxExpProf = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        modelo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cPassageiros = new javax.swing.JTextField();
        hVoo = new javax.swing.JTextField();
        proxTipoAeronave = new javax.swing.JButton();
        pesquisar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Consulta");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/cadastroPilotos/imagens/aviao.png"))); // NOI18N
        setName("Consulta"); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Dados Pessoais:");

        nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeActionPerformed(evt);
            }
        });

        Nome.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Nome.setText("Nome: ");

        Endereco.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Endereco.setText("Endereço:");

        try {
            fone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        Registro.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Registro.setText("Fone:");

        Email.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Email.setText("E-mail:");

        Breve.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Breve.setText("Número do Brevê:");

        nBreve.setName(""); // NOI18N
        nBreve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nBreveActionPerformed(evt);
            }
        });

        Fone.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Fone.setText("Registro Profissional:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Digite o número do brevê para procurar um piloto:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Titulação:");

        Breve1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Breve1.setText("Ano de Conclusão:");

        try {
            anoConc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        Breve2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Breve2.setText("Nome da Instituição:");

        Breve3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Breve3.setText("Cidade:");

        try {
            uf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("UU")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        Breve4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Breve4.setText("UF:");

        proxTitulacao.setText(">>>");
        proxTitulacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proxTitulacaoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Experiência Profissional:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("Data de Início:");

        try {
            dInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setText("Data de Término:");

        try {
            dTermino.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setText("Empresa:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel8.setText("Cidade:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel9.setText("Estado:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel10.setText("Descrição da Atividade:");

        descricao.setColumns(20);
        descricao.setRows(5);
        jScrollPane1.setViewportView(descricao);

        proxExpProf.setText(">>>");
        proxExpProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proxExpProfActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel12.setText("Modelo:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel13.setText("Capacidade de Passageiros:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel14.setText("Horas de Vôo:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Tipo de Aeronave:");

        proxTipoAeronave.setText(">>>");
        proxTipoAeronave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proxTipoAeronaveActionPerformed(evt);
            }
        });

        pesquisar.setText("Pesquisar");
        pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(826, Short.MAX_VALUE)
                .addComponent(pesquisar)
                .addGap(83, 83, 83))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator4)
                    .addComponent(jSeparator3)
                    .addComponent(jSeparator2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(hVoo))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cPassageiros, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(dInicio))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(dTermino, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel9))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(estado)
                                            .addComponent(nCidade)
                                            .addComponent(empresa, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(12, 12, 12)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Breve1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(anoConc))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Breve2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(nomeInt, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Breve3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Breve4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(uf, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(proxTitulacao)
                            .addComponent(proxExpProf)
                            .addComponent(proxTipoAeronave))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator1)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextField1))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(Breve)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(nBreve, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(Fone)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(registroProf, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Endereco)
                                        .addComponent(Nome))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(nome)
                                        .addComponent(endereco)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(Email)
                                    .addGap(32, 32, 32)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(fone)
                                        .addComponent(email))))
                            .addGap(163, 163, 163))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(Registro))
                            .addGap(0, 823, Short.MAX_VALUE)))
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pesquisar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 215, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Breve1)
                    .addComponent(Breve3)
                    .addComponent(anoConc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Breve2)
                    .addComponent(Breve4)
                    .addComponent(nomeInt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(proxTitulacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(dInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addComponent(dTermino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(empresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(nCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(proxExpProf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(cPassageiros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(hVoo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(proxTipoAeronave)
                .addGap(112, 112, 112))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(4, 4, 4)
                    .addComponent(jLabel4)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Nome))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Endereco))
                    .addGap(5, 5, 5)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Registro)
                        .addComponent(fone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Email))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Fone)
                        .addComponent(nBreve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Breve)
                        .addComponent(registroProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(664, Short.MAX_VALUE)))
        );

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 978, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 887, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeActionPerformed

    private void nBreveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nBreveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nBreveActionPerformed

    private void proxTitulacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proxTitulacaoActionPerformed
        // TODO add your handling code here:
        indiceTitulacao++;

        if (Persistencia.getListaPiloto().get(indice).getTitulacao().size() == indiceTitulacao) {
            indiceTitulacao = 0;
        }
        t = Persistencia.getListaPiloto().get(indice).getTitulacao().get(indiceTitulacao);
        anoConc.setText(String.valueOf(p.getTitulacao().get(indiceTitulacao).getAnoConclusao())); 
        nomeInt.setText(p.getTitulacao().get(indiceTitulacao).getNomeInstituicao());
        cidade.setText(p.getTitulacao().get(indiceTitulacao).getCidade());
        uf.setText(p.getTitulacao().get(indiceTitulacao).getuF()); 

    }//GEN-LAST:event_proxTitulacaoActionPerformed

    private void pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarActionPerformed

        for (int i = 0; i < listaPilotos.size(); i++) {
            if (listaPilotos.get(i).getBreve().equalsIgnoreCase(jTextField1.getText())) {
                proxExpProf.setEnabled(true); //Reabilita o botão
                proxTipoAeronave.setEnabled(true); //Reabilita o botão
                proxTitulacao.setEnabled(true); //Reabilita o botão
                encontrou = true;
                indice = i;

                p = listaPilotos.get(indice);
                nome.setText(p.getNome());
                endereco.setText(p.getEndereco());
                fone.setText(p.getFone());
                fone.setValue(p.getFone());
                email.setText(p.getMail());
                nBreve.setText(p.getBreve());
                registroProf.setText(p.getRegistroP());



                anoConc.setText(String.valueOf(p.getTitulacao().get(indiceTitulacao).getAnoConclusao()));
                nomeInt.setText(p.getTitulacao().get(indiceTitulacao).getNomeInstituicao()); 
                cidade.setText(p.getTitulacao().get(indiceTitulacao).getCidade()); 
                uf.setText(p.getTitulacao().get(indiceTitulacao).getuF());


                dInicio.setText(p.getExpProfissional().get(indiceExpProfissional).getDataI());
                dTermino.setText(p.getExpProfissional().get(indiceExpProfissional).getDataT());
                empresa.setText(p.getExpProfissional().get(indiceExpProfissional).getEmpresa());
                nCidade.setText(p.getExpProfissional().get(indiceExpProfissional).getNCidade());
                estado.setText(p.getExpProfissional().get(indiceExpProfissional).getEstado());
                descricao.setText(p.getExpProfissional().get(indiceExpProfissional).getDescricaoA());

                modelo.setText(p.getTipoAeronave().get(indiceTipoAeronave).getModelo());
                cPassageiros.setText(String.valueOf(p.getTipoAeronave().get(indiceTipoAeronave).getCapacidadePassageiros()));
                hVoo.setText(String.valueOf(p.getTipoAeronave().get(indiceTipoAeronave).getHorasDeVoo()));

                break;
            }
        }
        if (!encontrou) {
            JOptionPane.showMessageDialog(null, "Nenhum Piloto Encontrado", "Não Encontrado", JOptionPane.ERROR_MESSAGE);
        } else if (jTextField1.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o Campo Antes de Realizar uma Consulta", null, JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_pesquisarActionPerformed
    
    private void proxExpProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proxExpProfActionPerformed
        // TODO add your handling code here:
        indiceExpProfissional++;
        if (Persistencia.getListaPiloto().get(indice).getExpProfissional().size() == indiceExpProfissional) {
            indiceExpProfissional = 0;
        }
        exp = Persistencia.getListaPiloto().get(indice).getExpProfissional().get(indiceExpProfissional);
        dInicio.setText(exp.getDataI());
        dTermino.setText(exp.getDataT());
        empresa.setText(exp.getEmpresa());
        nCidade.setText(exp.getNCidade());
        estado.setText(exp.getEstado());
        descricao.setText(exp.getDescricaoA());
    }//GEN-LAST:event_proxExpProfActionPerformed

    private void proxTipoAeronaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proxTipoAeronaveActionPerformed
        // TODO add your handling code here:
        indiceTipoAeronave++;
        if (Persistencia.getListaPiloto().get(indice).getTipoAeronave().size() == indiceTipoAeronave) {
            indiceTipoAeronave = 0;
        }
        aeronave = Persistencia.getListaPiloto().get(indice).getTipoAeronave().get(indiceTipoAeronave);
        modelo.setText(aeronave.getModelo());
        cPassageiros.setText(String.valueOf(aeronave.getCapacidadePassageiros()));
        hVoo.setText(String.valueOf(aeronave.getHorasDeVoo()));
    }//GEN-LAST:event_proxTipoAeronaveActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Breve;
    private javax.swing.JLabel Breve1;
    private javax.swing.JLabel Breve2;
    private javax.swing.JLabel Breve3;
    private javax.swing.JLabel Breve4;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel Endereco;
    private javax.swing.JLabel Fone;
    private javax.swing.JLabel Nome;
    private javax.swing.JLabel Registro;
    private javax.swing.JFormattedTextField anoConc;
    private javax.swing.JTextField cPassageiros;
    private javax.swing.JTextField cidade;
    private javax.swing.JFormattedTextField dInicio;
    private javax.swing.JFormattedTextField dTermino;
    private javax.swing.JTextArea descricao;
    private javax.swing.JTextField email;
    private javax.swing.JTextField empresa;
    private javax.swing.JTextField endereco;
    private javax.swing.JTextField estado;
    private javax.swing.JFormattedTextField fone;
    private javax.swing.JTextField hVoo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField modelo;
    private javax.swing.JTextField nBreve;
    private javax.swing.JTextField nCidade;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField nomeInt;
    private javax.swing.JButton pesquisar;
    private javax.swing.JButton proxExpProf;
    private javax.swing.JButton proxTipoAeronave;
    private javax.swing.JButton proxTitulacao;
    private javax.swing.JTextField registroProf;
    private javax.swing.JFormattedTextField uf;
    // End of variables declaration//GEN-END:variables
}
