/* Projeto MPS - Cadastro de pilotos de aeronave
 * 
 * Professora: Raoni Kulesza
 * 
 * Grupo: Angelina Sales
          Jorismar Barbosa
          Nycholas de Sousa
 * 
 * Descrição da Classe: Classe principal contendo jDesktopPane("Gerenciador da interface")
 */
package cadastroPilotos;


import javax.swing.ImageIcon;
import javax.swing.JFrame;

public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        Persistencia.checkFiles();
        Persistencia.setupLer();
        Persistencia.readRecords();
        Persistencia.cleanupLer();
        initComponents(); //Default NetBeans
        imagem1 = new ImageIcon(getClass().getResource("imagens/aviao.png")); //Icone
        setIconImage(imagem1.getImage()); //Icone
        setExtendedState(JFrame.MAXIMIZED_BOTH); //inicia com a tela principal maximizada
        setLocationRelativeTo(null); //Posição da tela ao iniciar a aplicação

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        BarraDeControle = new javax.swing.JMenuBar();
        Cadastro = new javax.swing.JMenu();
        Cadastrar = new javax.swing.JMenuItem();
        Consultar = new javax.swing.JMenuItem();
        Alterar = new javax.swing.JMenuItem();
        Sobre = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de pilotos de aeronaves");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jDesktopPane1.setBackground(new java.awt.Color(240, 240, 240));

        Cadastro.setText("Cadastro");

        Cadastrar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        Cadastrar.setText("Cadastrar");
        Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarActionPerformed(evt);
            }
        });
        Cadastro.add(Cadastrar);

        Consultar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        Consultar.setText("Consultar");
        Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarActionPerformed(evt);
            }
        });
        Cadastro.add(Consultar);

        Alterar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        Alterar.setText("Alterar");
        Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlterarActionPerformed(evt);
            }
        });
        Cadastro.add(Alterar);

        BarraDeControle.add(Cadastro);

        Sobre.setText("Sobre");

        jMenuItem1.setText("Desenvolvedores");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        Sobre.add(jMenuItem1);

        jMenuItem2.setText("Índice");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        Sobre.add(jMenuItem2);

        BarraDeControle.add(Sobre);

        setJMenuBar(BarraDeControle);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1253, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 857, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarActionPerformed
        // Açao do jMenuItem
        Cadastro telaCadastro = new Cadastro(); //Instanciação
        jDesktopPane1.add(telaCadastro); //Adiciona tela ao jDesktopPane
        telaCadastro.setVisible(true); //Deixa a tela visível
    }//GEN-LAST:event_CadastrarActionPerformed

    private void AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlterarActionPerformed
        // Açao do jMenuItem
        Alterar telaAlterar = new Alterar(); //Instanciação
        jDesktopPane1.add(telaAlterar); //Adiciona tela ao jDesktopPane
        telaAlterar.setVisible(true); //Deixa a tela visível
    }//GEN-LAST:event_AlterarActionPerformed

    private void ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarActionPerformed
        // Açao do jMenuItem
        Consulta telaConsulta = new Consulta(); //Instanciação
        jDesktopPane1.add(telaConsulta); //Adiciona tela ao jDesktopPane
        telaConsulta.setVisible(true); //Deixa a tela visível
    }//GEN-LAST:event_ConsultarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // Açao do jMenuItem
        Sobre desenvolvedores = new Sobre(); //Instanciação
        jDesktopPane1.add(desenvolvedores); //Adiciona tela ao jDesktopPane
        desenvolvedores.setVisible(true); //Deixa a tela visível
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Persistencia.setupGravar();
        Persistencia.addRecords();
        Persistencia.cleanupGravar(); //grava dados, fecha arquivo
        dispose(); //libera os recursos
        System.exit(0); //Encerra o programa liberando a memória.
    }//GEN-LAST:event_formWindowClosing

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        Indice i = new Indice(); //Instanciação
        jDesktopPane1.add(i); //Adiciona tela ao jDesktopPane
        i.setVisible(true); //Deixa a tela visível
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);

            }
        });

    } //Fim do método main
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Alterar;
    private javax.swing.JMenuBar BarraDeControle;
    private javax.swing.JMenuItem Cadastrar;
    private javax.swing.JMenu Cadastro;
    private javax.swing.JMenuItem Consultar;
    private javax.swing.JMenu Sobre;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    // End of variables declaration//GEN-END:variables
    private ImageIcon imagem1;
} //Fim da classe Principal
